trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          
          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'
  
  - stage: Development
    dependsOn: Build
    jobs:
      - job: DeployDevelopment
        steps:
          - download: current
            artifact: drop
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription_Accumenta(1)(c85ec78d-8a5c-478e-abc8-8c32d9ae4e05)'
              appType: 'webApp'
              WebAppName: 'Pellisambandhalu-Dev'
              packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
            displayName: 'Deploy to Development'

  - stage: Staging
    dependsOn: Development
    jobs:
      - job: DeployStaging
        steps:
          - download: current
            artifact: drop
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription_Accumenta(1)(c85ec78d-8a5c-478e-abc8-8c32d9ae4e05)'
              appType: 'webApp'
              WebAppName: 'Pellisambandhalu-Staging'
              packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
            displayName: 'Deploy to Staging'

  - stage: Production
    dependsOn: Staging
    jobs:
      - job: DeployProduction
        steps:
          - download: current
            artifact: drop
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription_Accumenta(1)(c85ec78d-8a5c-478e-abc8-8c32d9ae4e05)'
              appType: 'webApp'
              WebAppName: 'Pellisambandhalu'
              packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
            displayName: 'Deploy to Production'

